[package]
name = "etherscan"
version = "0.1.0"
edition = "2018"

[dependencies]
filebuffer = "0.4.0"
structopt = { version = "0.2", default-features = false }
env_logger = "0.7.1"
log = "0.4"
hex = { version = "0.3"}
byteorder = "1.3.4"
rlimit = "0.3.0"
