name: Autobuild
on: [pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TrueBlocks repo
        uses: actions/checkout@v2
      - name: Install prerequistes
        run: |
          sudo apt-get install build-essential git cmake python python-dev libcurl3-dev clang-format jq tree
      - name: Build TrueBlocks
        run: |
          mkdir -p build && cd build
          cmake ../src
          make -j 4
      - name: Finish
        run: |
          echo "Build status: ${{ job.status }}"